test:
  adapter: postgresql
  database: bucketlister_test
  encoding: utf8
  pool: 5
  host: localhost

development:
  adapter: postgresql
  database: bucketlister_development
  pool: 5
  host: localhost
  encoding: utf8
